### PR TITLE
Fix formatting of build file for consistency

### PR DESCRIPTION
**Pull request by anuraaga**
This commit is under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tim-mwangi** [comment]
Thanks @anuraaga for this!

**Comment by dnielsen** [comment]
Hi @anuraaga, Would you mind confirming that your contribution is under the Apache 2.0 license terms?

**Comment by anuraaga** [comment]
Hi @dnielsen - yes I confirm this contribution is under the Apache 2.0 license terms.

**Comment by anuraaga** [comment]
Also you may already be planning something but just in case I've had good results using cla assistant :) https://cla-assistant.io/

**Comment by buchi-busireddy** [comment]
@anuraaga FYI, I'm closing and reopening this PR to trigger the builds. There was some setting that we had to tweak to get the builds working.

**Pull request merged**
