### PR TITLE
adds supports for pre-creation of topics

### PR DESCRIPTION
**Pull request by kotharironak**
See more details on - https://github.com/hypertrace/kafka-streams-framework/issues/5
And framework PR - https://github.com/hypertrace/kafka-streams-framework/pull/6

### CODE REVIEW

**Comment by adriancole** [comment]
one consideration is that this will eventually move to the macrorepo hypertrace-ingester, who should also house our test image for kafka-zookeeper. If the precreation is only for quick start, it could be handled as a layer in that image, particularly when they are in the same repo it won't be hard to track.

**Comment by kotharironak** [comment]
Merged these changes as part of the PR - https://github.com/hypertrace/span-normalizer/pull/18

**Comment by kotharironak** [comment]
@adriancole Yes, right if we are going to keep this pre-creation only for quick-start. But, I was thinking of exploring the option of removal of helm pre-install hook for this. If that's not the case, we can optimize this further as suggested.

**Comment by kotharironak** [comment]
closing this PR.

**Comment by kotharironak** [comment]
closing this as no longer required

**Pull request closed without merging**
